# Generated by Django 6.0.4 on 2026-09-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0002_alter_userprofile_rank_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='Passionate Python & DSA Practitioner.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_topics',
            field=models.CharField(blank=True, default='Python, Algorithms, Dynamic Programming', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
